# Generated by Django 3.2.6 on 2021-08-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210806_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='team',
            new_name='Team',
        ),
    ]
