# Generated by Django 3.2.6 on 2021-08-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_team_member_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Team',
            new_name='team',
        ),
    ]
