# Generated by Django 3.2.6 on 2021-10-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_member_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dev_title',
            field=models.CharField(choices=[('Front Developer', 'Front Developer'), ('Back End Developer', 'Back End Developer'), ('Team Lead', 'Team Lead'), ('Technical Head', 'Technical Head'), ('Project Manager', 'Project Manager'), ('DevOps', 'DevOps'), ('Database Engineer', 'Database Engineer'), ('Solution Architecture', 'Solution Architecture'), ('QA', 'QA'), ('Support Team', 'Support Team'), ('Business Annalists', 'Business Annalists')], max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='work_hours',
            field=models.CharField(choices=[('8 Hours', '8'), ('6 Hours', '6'), ('4 Hours', '4'), ('10 Hours', '10'), ('2 Hours', '2')], max_length=255),
        ),
    ]
