# Generated by Django 3.2.6 on 2021-08-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_auto_20210809_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_story_committed', models.IntegerField(default=0)),
                ('total_story_completed', models.IntegerField(default=0)),
                ('no_resource', models.IntegerField(default=0)),
                ('availabe_resource_hrs', models.IntegerField(default=0)),
                ('total_efforts', models.IntegerField(default=0)),
                ('total_efforts_used', models.IntegerField(default=0)),
                ('total_storypoints', models.IntegerField(default=0)),
                ('total_storypoints_achieved', models.IntegerField(default=0)),
                ('total_bugs_report_qa', models.IntegerField(default=0)),
                ('total_bugs_report_valid_qa', models.IntegerField(default=0)),
                ('total_bugs_report_prod', models.IntegerField(default=0)),
                ('total_bugs_report_valid_prod', models.IntegerField(default=0)),
                ('total_bugs_resolved_qa', models.IntegerField(default=0)),
                ('total_bugs_resolved_prod', models.IntegerField(default=0)),
                ('comments', models.TextField()),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
