# Generated by Django 3.2.6 on 2021-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210809_0649'),
        ('projectcycle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcycle',
            name='project',
        ),
        migrations.AddField(
            model_name='projectcycle',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
