# Generated by Django 3.2.6 on 2021-10-06 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectcycle', '0002_auto_20210809_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcycle',
            old_name='availabe_resource_hrs',
            new_name='average_resource_hrs',
        ),
        migrations.AddField(
            model_name='projectcycle',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectcycle',
            name='planned_resource_hrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectcycle',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectcycle',
            name='total_working_days',
            field=models.IntegerField(default=0),
        ),
    ]
