# Generated by Django 3.2.6 on 2021-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcycle', '0003_auto_20211006_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcycle',
            name='isclose',
            field=models.BooleanField(default=False),
        ),
    ]
